module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/HRdlOPWj9lyBIEfLC3PPU6',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/otx26d.jpg',
    NEWSLETTER_JID: '120363351424590490@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'Warlord-md',
    OWNER_NAME: 'Wds_-_',
    OWNER_NUMBER: '254769677305',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © 𝒫𝑜𝓌𝑒𝓇𝑒𝒹 𝐵𝓎 wds',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb6jxRD7IUYbQfokIu2s',
};
